// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZOoY7tztZsT7ybM4qq8OXbJLmMfz4T8',
    appId: '1:982825286886:web:5f6b8c6f14e8a2a1ba4f27',
    messagingSenderId: '982825286886',
    projectId: 'nikemyshop',
    authDomain: 'nikemyshop.firebaseapp.com',
    storageBucket: 'nikemyshop.appspot.com',
    measurementId: 'G-WPBK2QY7H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlR2YJq_yaBGnlhItFNLN2Bwf1HcKUFPU',
    appId: '1:982825286886:android:2b6e54b221dd617cba4f27',
    messagingSenderId: '982825286886',
    projectId: 'nikemyshop',
    storageBucket: 'nikemyshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUoM_RIgV4qQFudzFKAUXQRMakPB4MtQ',
    appId: '1:982825286886:ios:92a48ceb826d3ae6ba4f27',
    messagingSenderId: '982825286886',
    projectId: 'nikemyshop',
    storageBucket: 'nikemyshop.appspot.com',
    iosBundleId: 'com.lesson0104.newShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUoM_RIgV4qQFudzFKAUXQRMakPB4MtQ',
    appId: '1:982825286886:ios:92a48ceb826d3ae6ba4f27',
    messagingSenderId: '982825286886',
    projectId: 'nikemyshop',
    storageBucket: 'nikemyshop.appspot.com',
    iosBundleId: 'com.lesson0104.newShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZOoY7tztZsT7ybM4qq8OXbJLmMfz4T8',
    appId: '1:982825286886:web:4056b4dde298d54cba4f27',
    messagingSenderId: '982825286886',
    projectId: 'nikemyshop',
    authDomain: 'nikemyshop.firebaseapp.com',
    storageBucket: 'nikemyshop.appspot.com',
    measurementId: 'G-45L2ZVS15P',
  );
}
